"""Convert a corpus of past AI-agent conversations into a trainable dataset
for this repo's existing `gated`/`expel` trainers -- so a real batch of
conversations gets the same validation-gated skill-editing every other
environment here gets, not a one-off script.

Why not `reflact`/`avo`: those need a *live, re-runnable* environment (they
roll out fresh episodes under the candidate skill and validate against a
held-out split of the SAME environment). A past conversation isn't
re-runnable -- there's no way to roll out "the same conversation" again
under a new skill. What conversations actually look like structurally is a
FIXED, pre-collected batch of labeled episodes, which is exactly what
`gated`/`expel` already consume (their `ctx.trajectories`, loaded once, never
re-rolled-out). Validation still needs held-out data to gate against, so
this also builds a dev/eval pool served by a real (LLM-as-judge) Environment
plugin -- see environments/conversation_judge/env.py for why that's a
legitimate Environment rather than a special case.

Usage:
    python convert_conversation.py --transcripts conv1.json conv2.json --name my-project
    python train_skill.py --env my-project --strategy gated
    python evaluate_skill.py --env my-project

Each transcript is segmented (by one LLM call per transcript) into episodes
-- one per user request, labeled success/failure by whether it was
corrected -- then split into a training pool (written as this repo's
standard trajectories.jsonl, used directly, no environment involved) and a
held-out dev/eval pool (served by conversation_judge for gated's validation
gate and evaluate_skill.py's final comparison).
"""

import argparse
import json
import random
from pathlib import Path

import yaml

from core.conversation import format_transcript
from core.llm import ModelClient
from core.skill import extract_json
from util import trainer_model_name

PROMPT_PATH = Path(__file__).parent / "prompts" / "segment_conversation.md"
ROOT_CONFIG_PATH = Path(__file__).parent / "config.yaml"
REPO_ROOT = Path(__file__).parent

DEFAULT_SKILL_TEMPLATE = """---
name: {name}
description: Lessons learned from past conversations, so the same mistakes aren't repeated.
---

# {name}
"""

CONFIG_TEMPLATE = """\
# Generated by convert_conversation.py from a corpus of past conversations.
# `conversation_judge` has no live environment to roll out against -- see
# environments/conversation_judge/env.py for how its validation gate works.
environment: conversation_judge

conversation_judge:
  # Absolute -- worker processes have no notion of "this experiment's
  # directory" the way util.resolve_path(env, ...) does for path fields
  # elsewhere, since the environment plugin only ever sees the merged config.
  episodes_path: "{episodes_path}"
  split_map:
    valid_seen: {{offset: 0, count: {n_valid_seen}}}
    valid_unseen: {{offset: {n_valid_seen}, count: {n_valid_unseen}}}

experiment:
  seed: 42
  max_steps: 5
  num_dev_tasks: {num_dev_tasks}
  num_eval_tasks: {num_eval_tasks}
  avo_dev_tasks_per_candidate: {num_dev_tasks}
  trainer_rounds: 3

paths:
  training_trajectories: "data/training/trajectories.jsonl"
  eval_baseline_trajectories: "data/evaluation/baseline_trajectories.jsonl"
  eval_skill_trajectories: "data/evaluation/skill_trajectories.jsonl"
  skill_dir: "skills"
  skill_file: "skills/SKILL.md"
  initial_skill_file: "skills/SKILL.initial.md"
  trainer_rounds_log: "results/trainer_rounds.json"
  results_summary: "results/summary.json"
  results_table: "results/summary.txt"
"""


def load_root_config() -> dict:
    with open(ROOT_CONFIG_PATH) as f:
        return yaml.safe_load(f)


def segment_conversation(client: ModelClient, model: str, temperature: float, max_tokens: int, transcript_text: str) -> list[dict]:
    prompt = PROMPT_PATH.read_text().format(transcript=transcript_text)
    raw_text, _usage = client.chat(
        model=model, messages=[{"role": "user", "content": prompt}], temperature=temperature, max_tokens=max_tokens,
    )
    data = extract_json(raw_text)
    if not data or not isinstance(data.get("episodes"), list):
        return []
    episodes = []
    for ep in data["episodes"]:
        if not isinstance(ep, dict) or "task" not in ep or "steps" not in ep:
            continue
        episodes.append({
            "task": str(ep["task"]),
            "steps": ep["steps"] if isinstance(ep["steps"], list) else [],
            "success": bool(ep.get("success", False)),
            "outcome_note": str(ep.get("outcome_note", "")),
        })
    return episodes


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--transcripts", nargs="+", required=True, help="One or more conversation transcript files (JSON turns or plain text).")
    parser.add_argument("--name", required=True, help="Experiment name -- writes to experiments/<name>/.")
    parser.add_argument("--dev-fraction", type=float, default=0.3, help="Fraction of episodes held out for the validation gate / final eval.")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    config = load_root_config()
    client = ModelClient(config)
    model = trainer_model_name(config)
    temperature = config["model"]["trainer_temperature"]
    max_tokens = config["model"]["trainer_max_tokens"]

    all_episodes = []
    for path in args.transcripts:
        transcript_text = format_transcript(Path(path).read_text())
        episodes = segment_conversation(client, model, temperature, max_tokens, transcript_text)
        print(f"{path}: segmented into {len(episodes)} episode(s) "
              f"({sum(1 for e in episodes if e['success'])} success, {sum(1 for e in episodes if not e['success'])} failure)")
        all_episodes.extend(episodes)

    if not all_episodes:
        raise SystemExit("No episodes extracted from any transcript -- nothing to write.")

    rng = random.Random(args.seed)
    rng.shuffle(all_episodes)
    n_dev = max(1, round(len(all_episodes) * args.dev_fraction)) if len(all_episodes) > 1 else 0
    dev_episodes, train_episodes = all_episodes[:n_dev], all_episodes[n_dev:]
    if not train_episodes:
        train_episodes, dev_episodes = all_episodes, []
        print("Warning: too few episodes to hold any out -- all episodes used for training, dev pool empty.")

    n_valid_seen = (len(dev_episodes) + 1) // 2
    n_valid_unseen = len(dev_episodes) - n_valid_seen

    exp_dir = REPO_ROOT / "experiments" / args.name
    (exp_dir / "data" / "training").mkdir(parents=True, exist_ok=True)
    (exp_dir / "skills").mkdir(parents=True, exist_ok=True)

    trajectories_path = exp_dir / "data" / "training" / "trajectories.jsonl"
    with open(trajectories_path, "w") as f:
        for i, ep in enumerate(train_episodes):
            f.write(json.dumps({
                "task": ep["task"], "task_id": f"train[{i}]", "steps": ep["steps"],
                "success": ep["success"], "total_tokens": 0,
            }) + "\n")
    print(f"\nWrote {len(train_episodes)} training episode(s) -> {trajectories_path}")

    dev_pool_path = exp_dir / "data" / "dev_pool.json"
    dev_pool_path.write_text(json.dumps(dev_episodes, indent=2))
    print(f"Wrote {len(dev_episodes)} held-out episode(s) -> {dev_pool_path} "
          f"({n_valid_seen} valid_seen / {n_valid_unseen} valid_unseen)")

    num_dev_tasks = max(1, min(n_valid_seen, 20)) if n_valid_seen else 0
    num_eval_tasks = max(1, n_valid_unseen) if n_valid_unseen else 0
    config_path = exp_dir / "config.yaml"
    config_path.write_text(CONFIG_TEMPLATE.format(
        episodes_path=str(dev_pool_path.resolve()),
        n_valid_seen=n_valid_seen, n_valid_unseen=n_valid_unseen,
        num_dev_tasks=num_dev_tasks, num_eval_tasks=num_eval_tasks,
    ))
    print(f"Wrote {config_path}")

    initial_skill_path = exp_dir / "skills" / "SKILL.initial.md"
    if not initial_skill_path.exists():
        initial_skill_path.write_text(DEFAULT_SKILL_TEMPLATE.format(name=args.name))
        print(f"Wrote {initial_skill_path}")

    print(f"\nRun: python train_skill.py --env {args.name} --strategy gated")
    if num_eval_tasks:
        print(f"Then: python evaluate_skill.py --env {args.name}")
    else:
        print("(No valid_unseen episodes -- add more transcripts before running evaluate_skill.py.)")


if __name__ == "__main__":
    main()
